# product-releases 栈：API(3090) + 下载站(8080)
# 宿主机 nginx：download.* → 8080；license.* → 3090（同一 API 进程）
# 执行：docker compose up -d --build
services:
  product-releases-api:
    build:
      context: .
    container_name: product-releases-api
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 3090
      DB_PATH: ./data/product-releases.db
    volumes:
      - product_releases_api_data:/app/data
    ports:
      - "3090:3090"
    restart: unless-stopped

  product-releases-app:
    build:
      context: ../product-releases-app
    container_name: product-releases-app
    depends_on:
      - product-releases-api
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  product_releases_api_data:
