/** 稳定 messageCode：业务层只抛 code，文案由 i18n 层生成 */
const SUCCESS_CODES = {
  REQUEST_COMPLETED: 'REQUEST_COMPLETED',
  TRIAL_STARTED: 'TRIAL_STARTED',
  PRO_REDEEMED: 'PRO_REDEEMED',
  PRO_ACTIVATION_CODE_SENT: 'PRO_ACTIVATION_CODE_SENT',
  DEVICE_LIMIT_UPDATED: 'DEVICE_LIMIT_UPDATED',
  PRO_REVOKED: 'PRO_REVOKED',
  PRO_RESTORED: 'PRO_RESTORED',
  LICENSE_REFRESHED: 'LICENSE_REFRESHED',
  ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS'
}

const ERROR_CODES = {
  SERVER_ERROR: 'SERVER_ERROR',
  INVALID_PARAMETERS: 'INVALID_PARAMETERS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  USERNAME_PASSWORD_REQUIRED: 'USERNAME_PASSWORD_REQUIRED',
  ADMIN_AUTH_NOT_CONFIGURED: 'ADMIN_AUTH_NOT_CONFIGURED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  JWT_SECRET_NOT_CONFIGURED: 'JWT_SECRET_NOT_CONFIGURED',
  PRODUCT_KEY_REQUIRED: 'PRODUCT_KEY_REQUIRED',
  PRODUCT_KEY_INVALID: 'PRODUCT_KEY_INVALID',
  STATS_COUNTER_NOT_FOUND: 'STATS_COUNTER_NOT_FOUND',
  LICENSE_SIGNING_KEY_NOT_CONFIGURED: 'LICENSE_SIGNING_KEY_NOT_CONFIGURED',
  INVALID_EMAIL: 'INVALID_EMAIL',
  MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
  INVALID_DEVICE_ID: 'INVALID_DEVICE_ID',
  INVALID_DEVICE_LIMIT_OVERRIDE: 'INVALID_DEVICE_LIMIT_OVERRIDE',
  ACTIVATION_CODE_INVALID: 'ACTIVATION_CODE_INVALID',
  DEVICE_LIMIT_REACHED: 'DEVICE_LIMIT_REACHED',
  ACTIVATION_CODE_ALREADY_SENT: 'ACTIVATION_CODE_ALREADY_SENT',
  ACTIVATION_CODE_POOL_EMPTY: 'ACTIVATION_CODE_POOL_EMPTY',
  EMAIL_NOT_CONFIGURED: 'EMAIL_NOT_CONFIGURED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  INVALID_LICENSE: 'INVALID_LICENSE',
  LICENSE_NOT_FOUND: 'LICENSE_NOT_FOUND',
  LICENSE_REVOKED: 'LICENSE_REVOKED',
  PRO_NOT_REVOKABLE: 'PRO_NOT_REVOKABLE',
  PRO_ALREADY_REVOKED: 'PRO_ALREADY_REVOKED',
  PRO_NOT_RESTORABLE: 'PRO_NOT_RESTORABLE',
  PRO_NOT_REVOKED: 'PRO_NOT_REVOKED'
}

module.exports = { SUCCESS_CODES, ERROR_CODES }
